### **Backend**

setup

In [ ]:
!pip install selenium
!pip install PyMySQL
!install SQLAlchemy

In [ ]:
from selenium import webdriver
import pandas as pd
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import time
from selenium.webdriver.common.action_chains import ActionChains
import pymysql
import sqlalchemy
import pymysql
import numpy as np
pymysql.install_as_MySQLdb()
driver=webdriver.Chrome('/Users/oscarwan/Downloads/chromedriver')
url = 'https://albert.nyu.edu/albert_index.html'
driver.get(url)

login to albert. After finish loading, then run the following block

In [ ]:
def reEnterCE(driver = driver):
    CEbutton = driver.find_elements(By.CSS_SELECTOR, '#nyuSSSHomeLinksStatic > div > div > ul > li:nth-child(4) > a')
    CEbutton[0].click()
    time.sleep(3)

    driver.switch_to.frame(2)
reEnterCE()

Find all terms and schools names

In [ ]:
selects = driver.find_elements(By.TAG_NAME, 'select')
terms = [selects[0].find_elements(By.TAG_NAME, 'option')[x+1].accessible_name for x in range(19)]
select = Select(selects[0])
select.select_by_visible_text(terms[0])
time.sleep(1)
schoolSelect = driver.find_element(By.CSS_SELECTOR, '#NYU_CEV_PUB_DER_ACAD_ORG')
schools = [x.accessible_name for x in schoolSelect.find_elements(By.TAG_NAME, 'option')][1:]
temp = schools[1]
schools[1] = schools[5]
schools[5] = temp

# **Set Up**

In [ ]:
!pip install -q streamlit
!pip install -q pyngrok

     |████████████████████████████████| 9.2 MB 5.3 MB/s
     |████████████████████████████████| 237 kB 33.4 MB/s
     |████████████████████████████████| 182 kB 37.3 MB/s
     |████████████████████████████████| 78 kB 3.4 MB/s
     |████████████████████████████████| 4.7 MB 22.3 MB/s
     |████████████████████████████████| 164 kB 4.6 MB/s
     |████████████████████████████████| 62 kB 236 kB/s
     |████████████████████████████████| 51 kB 3.5 MB/s
  Building wheel for validators (setup.py) ... done
     |████████████████████████████████| 761 kB 3.0 MB/s
  Building wheel for pyngrok (setup.py) ... done

In [ ]:
# Install the SQLAlchemy library if it is not installed
!sudo apt-get install python3-dev libmysqlclient-dev > /dev/null
!pip install mysqlclient > /dev/null
!sudo pip3 install -U sql_magic > /dev/null

In [ ]:
# Authenticate the NGROK

!ngrok authtoken 2IsJGcI3ocXzHKQx8jJdVKghVnC_4xppKXaiyvm3We12mrJY4 #register to get own authtoken

Authtoken saved to configuration file: /root/.ngrok2/ngrok.yml

# **Review DataFrame**

In [ ]:
#establish engine
import pandas as pd
from sqlalchemy import create_engine
import numpy as np
import matplotlib.pyplot as plt
conn_string = 'mysql://{user}:{password}@{host}:{port}/{db}?charset={encoding}'.format(
    user='daily_screamer', 
    password='sF5pxbMLBg8=', 
    host = 'jsedocc7.scrc.nyu.edu', 
    port     = 3306, 
    encoding = 'utf8',
    db = 'daily_screamer'
)
engine = create_engine(conn_string)
cas = pd.read_sql("select * from CASCE1", con=engine)
stern = pd.read_sql("select * from SternCE1", con=engine)

In [ ]:
#check Stern dataframe
pd.read_sql("SELECT * FROM SternCE1", con = engine)

,index,courseID,courseCode,courseSection,courseName,instructor,totalResponses,responseRate,OverallEvaluationCourse,clearlyStatedObjectives,wellOrganized,intellectuallyStimulating,overallEvaluationInstructor,conduciveToLearning,providedHelpfulFeedback,qualityPCA
0,0,3103,ACCT-UB 1,001,Prin of Financial Acctg (Lecture),"Yiwei Dou, Xiaojing Meng",11,0.344,4.3,4.5,4.6,4.4,4.6,4.5,4.5,0.703390
1,1,1222,FINC-UB 86,040,Chinese Financial Markets (Lecture),Matthew Richardson,16,0.390,4.8,4.8,4.4,4.8,4.7,4.7,4.5,1.887777
2,2,1221,MGMT-UB 1,040,Management and Organizations (Lecture),Elinor Flynn,9,0.333,4.8,4.8,4.9,4.8,4.8,4.9,4.6,2.608919
3,3,1224,MGMT-UB 1,041,Management and Organizations (Lecture),Katia Meggiorin,9,0.321,4.3,4.4,4.6,4.4,4.7,4.8,3.9,0.552649
4,4,1114,FINC-UB 86,040,Chinese Financial Markets (Lecture),Matthew Richardson,15,0.577,4.4,4.4,4.4,4.2,4.7,4.5,3.8,-0.020374
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1698,1698,10954,STAT-UB 103,006,Stats F/Bus Cntl Regress & Forecasting Models ...,Halina Frydman,41,0.569,3.5,4.1,3.7,3.5,3.3,3.5,3.8,-4.375040
1699,1699,1194,MKTG-UB 1,040,Intro to Marketing (Lecture),Carol Pluzinski,8,0.157,4.6,5.0,4.8,4.5,4.9,4.8,4.5,2.216348
1700,1700,1195,MKTG-UB 40,040,Entertainment & Media Industries (Lecture),Kenneth J Krushel,14,0.933,4.7,4.6,4.8,4.4,4.9,4.8,4.5,1.841034
1701,1701,11515,MKTG-UB 40,002,Entertainment & Media Industries (Lecture),Kenneth J Krushel,23,0.561,4.7,4.7,4.7,4.6,4.7,4.5,4.6,1.654367
1702,1702,20421,STAT-UB 14,001,Intro Theory of Probability (Lecture),Aaron Tenenbein,17,0.347,4.3,4.4,4.2,4.6,4.5,4.5,4.4,0.314631

In [ ]:
cas
#cas.insert(7, 'qualityRating', pd.qcut(cas.qualityPCA, 5, labels = ['horrendous', 'bad','decent','good','excellent']))
cas.insert(7, 'difficultyRating', pd.qcut(cas.difficultyPCA, 5, labels = ['very easy', 'easy','average','challenging','very challenging']))
#cas['difficultyRating'] = pd.qcut(cas.difficultyPCA, 5, labels = ['very easy', 'easy','average','challenging','very challenging'])

#stern['qualityRating'] = pd.qcut(stern.qualityPCA, 5, labels = ['horrendous', 'bad','decent','good','excellent'])

In [ ]:
cas

,level_0,index,courseID,courseCode,courseSection,courseName,instructor,difficultyRating,qualityRating,totalResponses,...,conduciveToLearning.,helpfulFeedback,helpedMeLearn.,eencouragedParticipation.,facilitateDiscussion,openToQuestions,accessibleToStudents,inclusion,qualityPCA,difficultyPCA
0,0,0,2752,ANTH-UA 1,001,"Culture, Power, Society (Lecture)",Murray Laura,average,bad,5,...,4.4,4.4,4.4,4.6,4.2,4.6,4.4,4.4,-0.089243,0.123298
1,1,1,2722,ANTH-UA 1,001,"Culture, Power, Society (Lecture)",Anisha Chadha,very easy,good,6,...,4.7,4.7,4.7,5.0,4.8,4.8,4.8,4.8,2.356668,-0.928563
2,2,2,2798,ANTH-UA 1,060,"Culture, Power, Society (Lecture)",Anisha Chadha,very easy,good,6,...,4.7,4.7,4.7,5.0,4.8,4.8,4.8,4.8,2.356668,-0.928563
3,3,3,2732,ANTH-UA 2,001,Human Evolution (Lecture),Alejandra Ortiz,very challenging,horrendous,4,...,4.0,4.5,4.3,3.3,2.8,3.5,4.3,4.3,-3.900977,1.301798
4,4,4,2723,ANTH-UA 2,001,Human Evolution (Lecture),paola cerrito,very challenging,horrendous,6,...,3.7,3.0,3.0,3.8,3.0,3.8,4.0,3.7,-6.500822,0.840551
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9662,9662,9662,23356,DRLIT-UA 175,002,Topics: (Lecture),Eugenio Refini,easy,good,17,...,4.9,4.9,4.9,4.9,4.9,4.9,5.0,4.9,2.787881,-0.579763
9663,9663,9663,21366,DRLIT-UA 185,001,Topics: (Seminar),Yoon Jeong Oh,very challenging,decent,9,...,4.3,4.7,4.6,4.4,4.3,4.7,4.8,4.7,1.186910,0.839978
9664,9664,9664,8269,EAST-UA 226,001,Introduction to Classical Chinese (Lecture),Shiqi Liao,very challenging,decent,3,...,4.7,4.7,4.7,4.3,4.3,4.0,4.3,4.3,0.986588,1.810650
9665,9665,9665,10265,ENGL-UA 201,002,Reading as a Writer (Seminar),Marie-Christine Hyland,very easy,decent,10,...,4.7,4.7,4.6,4.8,4.8,5.0,4.9,4.8,0.882117,-1.976866
9666,9666,9666,19937,ENGL-UA 545,001,Colloq:19 Century (Colloquium),Peter Nicholls,challenging,excellent,10,...,5.0,4.7,5.0,4.9,4.8,4.8,4.9,4.9,3.899822,0.616750

# **Code for StreamLit**

In [ ]:
def select_quality_and_difficulty(quality, difficulty, department = None, showCE = False):
  df = cas
  q = cas.qualityPCA.values
  d = cas.difficultyPCA.values

  diffPercentiles = np.percentile(d, [0, 20, 40, 60, 80, 100])
  qualPercentiles = np.percentile(q, [0, 20, 40, 60, 80, 100])

  indices = np.argwhere((d >= diffPercentiles[difficulty]) & (d <= diffPercentiles[difficulty+1]) & (q>=qualPercentiles[quality]) & (q<=qualPercentiles[quality+1])).flatten()

  if showCE:
    result = df.iloc[indices]
  else:
    result = df.loc[indices][['courseCode',	'courseSection',	'courseName',	'instructor']]

  if department:
    return result[result.courseCode.str.contains(str.upper(department))]

  return result

def plotCourseOn2D(course, courseCode):
  plt.scatter(cas.qualityPCA, cas.difficultyPCA, label = "All Courses", s = 2)
  plt.scatter(course.qualityPCA, course.difficultyPCA, label = "All %s" % courseCode, s = 6, color = "chartreuse")
  plt.scatter(course.qualityPCA.mean(), course.difficultyPCA.mean(), label = "Average of %s" % courseCode, color = "orange")
  plt.xlabel("Overall Quality")
  plt.ylabel("Difficulty")
  plt.legend()

In [ ]:
stern
stern.insert(6, 'qualityRating', pd.qcut(stern.qualityPCA, 5, labels = ['horrendous', 'bad','decent','good','excellent']))
stern

,index,courseID,courseCode,courseSection,courseName,instructor,qualityRating,totalResponses,responseRate,OverallEvaluationCourse,clearlyStatedObjectives,wellOrganized,intellectuallyStimulating,overallEvaluationInstructor,conduciveToLearning,providedHelpfulFeedback,qualityPCA
0,0,3103,ACCT-UB 1,001,Prin of Financial Acctg (Lecture),"Yiwei Dou, Xiaojing Meng",decent,11,0.344,4.3,4.5,4.6,4.4,4.6,4.5,4.5,0.703390
1,1,1222,FINC-UB 86,040,Chinese Financial Markets (Lecture),Matthew Richardson,good,16,0.390,4.8,4.8,4.4,4.8,4.7,4.7,4.5,1.887777
2,2,1221,MGMT-UB 1,040,Management and Organizations (Lecture),Elinor Flynn,excellent,9,0.333,4.8,4.8,4.9,4.8,4.8,4.9,4.6,2.608919
3,3,1224,MGMT-UB 1,041,Management and Organizations (Lecture),Katia Meggiorin,decent,9,0.321,4.3,4.4,4.6,4.4,4.7,4.8,3.9,0.552649
4,4,1114,FINC-UB 86,040,Chinese Financial Markets (Lecture),Matthew Richardson,decent,15,0.577,4.4,4.4,4.4,4.2,4.7,4.5,3.8,-0.020374
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1698,1698,10954,STAT-UB 103,006,Stats F/Bus Cntl Regress & Forecasting Models ...,Halina Frydman,horrendous,41,0.569,3.5,4.1,3.7,3.5,3.3,3.5,3.8,-4.375040
1699,1699,1194,MKTG-UB 1,040,Intro to Marketing (Lecture),Carol Pluzinski,excellent,8,0.157,4.6,5.0,4.8,4.5,4.9,4.8,4.5,2.216348
1700,1700,1195,MKTG-UB 40,040,Entertainment & Media Industries (Lecture),Kenneth J Krushel,good,14,0.933,4.7,4.6,4.8,4.4,4.9,4.8,4.5,1.841034
1701,1701,11515,MKTG-UB 40,002,Entertainment & Media Industries (Lecture),Kenneth J Krushel,good,23,0.561,4.7,4.7,4.7,4.6,4.7,4.5,4.6,1.654367
1702,1702,20421,STAT-UB 14,001,Intro Theory of Probability (Lecture),Aaron Tenenbein,decent,17,0.347,4.3,4.4,4.2,4.6,4.5,4.5,4.4,0.314631

In [12]:
%%writefile CE.py
import streamlit as st
import pandas as pd
import numpy as np
from scipy.stats import percentileofscore
from cachetools import cached
import matplotlib.pyplot as plt

PAGE_CONFIG = {"page_title":"More Examples","page_icon":"💯","layout":"centered"}
st.set_page_config(**PAGE_CONFIG)

from sqlalchemy import create_engine
conn_string = 'mysql://{user}:{password}@{host}:{port}/{db}?charset={encoding}'.format(
    user='daily_screamer', 
    password='sF5pxbMLBg8=', 
    host = 'jsedocc7.scrc.nyu.edu', 
    port     = 3306, 
    encoding = 'utf8',
    db = 'daily_screamer'
)
engine = create_engine(conn_string)

cas = pd.read_sql("SELECT * FROM CASCE1", engine)
stern = pd.read_sql("SELECT * FROM SternCE1", engine)

casQuality = cas['qualityPCA'].values
casDifficulty = cas['difficultyPCA'].values

casProfQuality = cas.groupby('instructor')['qualityPCA'].mean().values
casProfDifficulty = cas.groupby('instructor')['difficultyPCA'].mean().values

sternQuality = stern['qualityPCA'].values

cas.insert(7, 'qualityRating', pd.qcut(cas.qualityPCA, 5, labels = ['horrendous', 'bad','decent','good','excellent']))
cas.insert(7, 'difficultyRating', pd.qcut(cas.difficultyPCA, 5, labels = ['very easy', 'easy','average','challenging','very challenging']))

stern.insert(6, 'qualityRating', pd.qcut(stern.qualityPCA, 5, labels = ['horrendous', 'bad','decent','good','excellent']))

def hist_all_courses(sql, engine):
    df_courses = pd.read_sql_query(sql, con=engine)
    fig = df_courses.OverallEvaluationCourse.hist().get_figure()
    st.pyplot(fig) 


def show_course_based_on_difficulty(difficulty, df, department = None, show_CE_result = True):

    d = df['difficultyPCA'].values
    diffPercentiles = np.percentile(d, [0, 20, 40, 60, 80, 100])
    indices = np.argwhere((d >= diffPercentiles[difficulty]) & (d <= diffPercentiles[difficulty+1])).flatten()
    

    if show_CE_result:
        result = df.iloc[indices]
    else:
        try:
          result = df.loc[indices][['courseCode',	'courseSection',	'courseName',	'instructor', 'qualityRating', 'difficultyRating']]
        except:
          result = df.loc[indices][['courseCode',	'courseSection',	'courseName',	'instructor', 'qualityRating']]

    result['quality'] = df['qualityPCA'].values[indices]


    if department:
        return result[result.courseCode.str.contains(str.upper(department))].sort_values('quality', ascending = False).drop('quality', axis = 1)
        
    return df.iloc[indices].drop('quality', axis = 1)



def show_course_based_on_quality(quality, df, department = None, show_CE_result = True, isCAS = True):

    d = df['qualityPCA'].values
    qualPercentiles = np.percentile(d, [0, 20, 40, 60, 80, 100])
    indices = np.argwhere((d >= qualPercentiles[quality]) & (d <= qualPercentiles[quality+1])).flatten()
    

    if show_CE_result:
        result = df.iloc[indices] 
    else:
        if isCAS:
            result = df.loc[indices][['courseCode',	'courseSection',	'courseName',	'instructor', 'qualityRating','difficultyRating']]
        else:
            result = df.loc[indices][['courseCode',	'courseSection',	'courseName',	'instructor','intellectuallyStimulating', 'qualityRating']]
   
    if department:
        if isCAS:
            result['difficulty'] = df['difficultyPCA'].values[indices]
            return result[result.courseCode.str.contains(str.upper(department))].sort_values('difficulty', ascending = False).drop('difficulty', axis = 1)
        else:
            return result[result.courseCode.str.contains(str.upper(department))]
      
    if isCAS:
        return df.iloc[indices].drop('quality', axis = 1)

    return df.iloc[indices]


def select_quality_and_difficulty(quality, difficulty, department = None, showCE = False):
  df = cas
  q = cas.qualityPCA.values
  d = cas.difficultyPCA.values

  diffPercentiles = np.percentile(d, [0, 20, 40, 60, 80, 100])
  qualPercentiles = np.percentile(q, [0, 20, 40, 60, 80, 100])

  indices = np.argwhere((d >= diffPercentiles[difficulty]) & (d <= diffPercentiles[difficulty+1]) & (q>=qualPercentiles[quality]) & (q<=qualPercentiles[quality+1])).flatten()

  if showCE:
    result = df.iloc[indices]
  else:
    result = df.loc[indices][['courseCode',	'courseSection',	'courseName',	'instructor', 'qualityRating','difficultyRating']]

  if department:
    return result[result.courseCode.str.contains(str.upper(department))]

  return result

def plotCourseOn2D(course, courseCode):
  fig, ax = plt.subplots(figsize = (10, 6))
  ax.scatter(cas.qualityPCA, cas.difficultyPCA, label = "All Courses", s = 2, color = "grey")
  ax.scatter(course.qualityPCA, course.difficultyPCA, label = "All %s" % courseCode, color = "lawngreen")
  ax.scatter(course.qualityPCA.mean(), course.difficultyPCA.mean(), label = "Average of %s" % courseCode, color = "cyan")
  ax.plot([cas.qualityPCA.mean()] * 2, [cas.difficultyPCA.min(), cas.difficultyPCA.max()], c = 'orange', label = 'Mean Quality')
  ax.plot([cas.qualityPCA.min(), cas.qualityPCA.max()], [cas.difficultyPCA.mean()]*2, c = 'orange', label = 'Mean Difficulty')
  ax.set_xlabel("Overall Quality")
  ax.set_ylabel("Difficulty")
  ax.legend()
  return fig

    

def main():
    st.title("Welcome!")
    st.subheader("Find your perfect match")
    menu = ["Home","CAS & Stern Course Summary", "CAS Course Search", "Stern Course Search"]
    choice = st.sidebar.selectbox('Menu',menu)
    if choice == 'Home':
      st.image(
            "https://media.designrush.com/inspirations/129660/conversions/_1521486208_365_NYUPreviewImage-preview.jpg",
            width=400, # Manually Adjust the width of the image as per requirement
        )


    if choice == 'CAS & Stern Course Summary':
        st.subheader("Below is a summary of the overall ratings for Stern courses")
        SQL_script = st.text_area(label='SQL Input', value='select OverallEvaluationCourse from SternCE1 LIMIT 10000')
        hist_all_courses(SQL_script, engine)
        st.subheader("Below is a summary of the overall ratings for CAS courses")
        SQL_script = st.text_area(label='SQL Input', value='select OverallEvaluationCourse from CASCE1 LIMIT 10000')
        hist_all_courses(SQL_script, engine)

    elif choice == 'CAS Course Search':
        st.subheader("Search Courses by Department Code", anchor=None)

        show_by_difficulty = st.checkbox('By Difficulty')
        difficulty = st.slider('**Select the difficulty level**', 1,5)
        show_by_quality = st.checkbox('By Quality')
        quality = st.slider('**Select the quality level**', 1,5)
        show_CE_result = st.checkbox('display course evaluation ratings')
        department_code_difficulty = st.text_input('**By CAS Department Code**')

        if department_code_difficulty:
          if show_by_difficulty and show_by_quality:
            result= select_quality_and_difficulty(difficulty-1,quality-1, department = department_code_difficulty, showCE = show_CE_result)
            st.dataframe(result)
          if not show_by_difficulty and show_by_quality:
            result = show_course_based_on_quality(quality-1, cas, department = department_code_difficulty, show_CE_result = show_CE_result, isCAS = True)
            st.dataframe(result)
          if show_by_difficulty and not show_by_quality:
            result = show_course_based_on_difficulty(difficulty-1, cas, department = department_code_difficulty, show_CE_result = show_CE_result)
            st.dataframe(result)

        st.markdown("""---""")

        st.subheader("Search Courses by Course Code", anchor=None)
        course_code = st.text_input('By CAS Course Code')
        if course_code:
          courses = cas[cas.courseCode == course_code].iloc[:, 2:] #pd.read_sql("select * from CASCE1 where courseCode = '" + course_code +"'", con=engine)
          Dpercentile = None
          Qpercentile = None
          if len(courses) != 0:
            st.dataframe(courses.sort_values('qualityPCA', ascending = False).drop(['qualityPCA', 'difficultyPCA'], axis = 1))
            Dpercentile = percentileofscore(casDifficulty, courses['difficultyPCA'].mean())
            Qpercentile = percentileofscore(casQuality, courses['qualityPCA'].mean())
          if Dpercentile:
            st.write("Difficulty percentile in CAS courses: %.3f" % Dpercentile)

          if Qpercentile:
            st.write("Quality percentile in CAS courses: %.3f" % Qpercentile)
            st.pyplot(plotCourseOn2D(courses, course_code))
          
          else: st.write("Course not found")

        st.markdown("""---""")

        st.subheader("Search Courses by Professor Name", anchor=None)
        professor_name = st.text_input('By CAS Professor Name')
        
        if professor_name:
          profs = cas[cas.instructor == professor_name].iloc[:, 2:]  #pd.read_sql("select * from CASCE1 where instructor = '" + professor_name +"'", con=engine)
          Dpercentile = None
          Qpercentile = None

          if len(profs) != 0:
            st.dataframe(profs.sort_values('qualityPCA', ascending = False).drop(['qualityPCA', 'difficultyPCA'], axis = 1))
            Dpercentile = percentileofscore(casProfDifficulty, profs['difficultyPCA'].mean())
            Qpercentile = percentileofscore(casProfQuality, profs['qualityPCA'].mean())
          if Dpercentile:
            st.write("Difficulty percentile in CAS professors: %.3f" % Dpercentile)

          if Qpercentile:
            st.write("Quality percentile in CAS professors: %.3f" % Qpercentile)
            st.pyplot(plotCourseOn2D(profs, professor_name))
          
          else: st.write("Course not found")


    elif choice == 'Stern Course Search':
        st.subheader("Search Department Courses by Quality", anchor=None)
        quality = st.slider('Select the quality level', 1,5)
        show_CE_result = st.checkbox('display course evaluation ratings')
        department_code_stern = st.text_input('By Stern Department Code')
        if department_code_stern:
            result = show_course_based_on_quality(quality-1, stern, department = department_code_stern, show_CE_result = show_CE_result, isCAS = False)
            st.dataframe(result)

        st.markdown("""---""")
       
        st.subheader("Search Courses by Course Code", anchor=None)
        course_code_stern = st.text_input('By Stern Course Code')
        if course_code_stern:
            st.dataframe(stern[stern.courseCode == course_code_stern])

        st.markdown("""---""")

        st.subheader("Search Courses by Professor Name", anchor=None)
        professor_name_stern = st.text_input('By Stern Professor Name')
        if professor_name_stern:
            st.dataframe(stern[stern.instructor == professor_name_stern].drop('qualityPCA', axis = 1)) 
                  
          
if __name__ == '__main__':
    main()

Overwriting CE.py

In [13]:
!streamlit run CE.py &>/dev/null &
#!streamlit run CE.py & npx localtunnel --port 8501

In [14]:
from pyngrok import ngrok
# Setup a tunnel to the streamlit port 8501
public_url = ngrok.connect(8501)

public_url

# **Stop**

In [ ]:
#input("press enter to stop the streamlit app")
# This is to stop the tunnel and streamlit
ngrok.kill()
!pkill streamlit